name: nikriksdb
on: push
jobs:
build-and-push-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the Nikriks Db image
run: |
       docker build . --tag ghcr.io/zarexalvindaria/nikriksapp-db:latest
       docker push ghcr.io/zarexalvindaria/nikriksapp-db:latest